global using Xunit;
global using Newtonsoft.Json;
global using TDD_NotasAluno.Domain.Model;
global using TDD_NotasAluno.Application;
global using TDD_NotasAluno.Application.Data;
global using TDD_NotasAluno.Domain;
global using TDD_NotasAluno.Infra.Data;
global using System.Net.Http.Json;
global using System.Dynamic;